apiVersion: v1
kind: Service
metadata:
  name: {{ include "terraform-registry.fullname" . }}-backend
  labels:
    {{- include "terraform-registry.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - name: http
      port: {{ .Values.service.backend.port }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.backend.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "terraform-registry.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
---
{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "terraform-registry.fullname" . }}-frontend
  labels:
    {{- include "terraform-registry.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - name: http
      port: {{ .Values.service.frontend.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "terraform-registry.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}
