apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: terraform-registry

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - configmap-frontend-nginx.yaml
  - secret.yaml
  - pvc.yaml
  - deployment-backend.yaml
  - deployment-frontend.yaml
  - service-backend.yaml
  - service-frontend.yaml
  - ingress.yaml
  - pdb.yaml

labels:
  - pairs:
      app.kubernetes.io/name: terraform-registry
      app.kubernetes.io/part-of: terraform-registry
    includeSelectors: true
